version: "3.7"

volumes:
  postgresql-data:
  pgadmin-data:

networks:
  AniRent:

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=AniRent
      - POSTGRES_USER=samael
      - POSTGRES_PASSWORD=samael
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - AniRent
    healthcheck:
      test: pg_isready -U samael -d AniRent
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 2s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "samael@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "samael"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    logging:
      driver: "none"
    ports:
      - 6969:80
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - AniRent

  backend:
    build: ./backend/
    container_name: AniRentBackend
    command: "python3 manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    volumes:
      - ./backend/:/app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - AniRent

  frontend:
    build: ./frontend/
    container_name: AniRentFrontend
    restart: unless-stopped
    volumes:
      - ./frontend/:/app
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - AniRent