# Generated by Django 3.2.11 on 2022-01-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.TextField(db_index=True)),
                ('cover', models.TextField()),
                ('releaseDate', models.CharField(max_length=10)),
                ('duration', models.TextField()),
                ('genres', models.TextField()),
                ('synopsis', models.TextField()),
                ('rating', models.CharField(max_length=4)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
