# Generated by Django 3.2.11 on 2022-05-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='reserved',
            field=models.TextField(default='false'),
        ),
    ]
