const MovieQueryModel = {
    GET_ALL_MOVIES:"GET_ALL_MOVIES",
    CREATE_MOVIE:"CREATE_MOVIE",
    UPDATE_MOVIE:"UPDATE_MOVIE",
    DELETE_MOVIE:"DELETE_MOVIE",
    RESERVE_MOVIE:"RESERVE_MOVIE",
    UNRESERVE_MOVIE:"UNRESERVE_MOVIE"
}

export default MovieQueryModel