# Generated by Django 3.2.11 on 2022-04-01 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('videostores', '0001_initial'),
        ('shelves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shelves', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='videostore',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shelves', to='videostores.videostore'),
        ),
    ]
